name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        type: choice
        description: select terraform action
        options:
        - apply
        - destroy
        required: true
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: 'Terraform'
    env:
      # AWS secrets
      AWS_ACCESS_KEY_ID: ${{ secrets.awsaccesskey }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.devopssecret }}
    defaults:
      run:
        working-directory: . 
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
   
      
      #uses: hashicorp/setup-terraform@v1
      #id: init
      run: terraform init
      working-directory: .
      
    - name: Terraform validate
      id: validate
      run: terraform validate
      working-directory: . 
  

     
    
    - name: Terraform plan
      #uses: hashicorp/setup-terraform@v1
      id: plan
      run: terraform plan -no-color
      working-directory: . 
      
      
    - name: Terraform apply
      if: ${{ github.event.inputs.terraform_action == 'apply' }}
      #uses: hashicorp/setup-terraform@v1
      run: terraform apply -auto-approve
      working-directory: . 
     
    
    - name: Terraform destroy
      if: ${{ github.event.inputs.terraform_action == 'destroy' }}
      run: terraform destroy -auto-approve
      working-directory: . 